# Generated by Django 5.1.7 on 2025-03-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='service_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
