# Generated by Django 5.1.7 on 2025-03-12 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_alter_bus_service_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_history',
            name='travelling_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking_history',
            name='ticket_no',
            field=models.IntegerField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
