# Generated by Django 5.1.7 on 2025-03-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_booking_history_travelling_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_history',
            name='ticket_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
